[package]
name = "taskmasterd"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
clap.workspace = true
anyhow.workspace = true
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
log = "0.4"
signal-hook = "0.3"
daemonize-me = "2.0"
